#Bu dosya, udm'nin konfigurasyon dosyalarinin template islemleri icin kullanilir.
#Eger konfigurasyon dosyalarinda degisiklik varsa, udm restart edilir.
- name: Check mandatory variables are defined
  assert:
    that:
         - container_name is defined
         - nrf_container_name is defined          
  when: deployment_type| default("vnf") == "cnf"

- block:
    - name: Get  ip address of ausf container
      ansible.builtin.include_role:
        name: get_container_ip_info
      vars:
        container: "{{container_name}}"
    - name: updated control ip address
      set_fact:
        control_ip: "{{container_ip.stdout}}"
    - name: Get  ip address of nrf container
      ansible.builtin.include_role:
        name: get_container_ip_info
      vars:
        container: "{{nrf_container_name}}"
    - name: updated nrf  ip address
      set_fact:
        nrf_ip: "{{container_ip.stdout}}"
    - name: Get config mount of container
      ansible.builtin.include_role:
        name: get_container_mount_info
  when: deployment_type == "cnf"

- name: Get recoveryTime info from NFProfile file
  ansible.builtin.include_role:
    name: json_parse
  vars:
    path: "{{ each_config_file.path }}"
    filename: "{{ each_config_file.filename }}"
    json_key: recoveryTime
  with_items: "{{ conf_files }}"
  when: each_config_file.filename == "NFProfile.json"
  loop_control:
       loop_var: each_config_file

- block:
  - name: Template udm settings file
    template: src=udm_settings_json.j2 dest="{{each_config_file.path}}/{{each_config_file.filename}}"
    diff: yes
    with_items: "{{ conf_files }}"
    when: each_config_file.filename == "settings.json"
    loop_control:
       loop_var: each_config_file

  - name: Template udm NFProfile file
    template: src=udm_nf_profile_json.j2 dest="{{each_config_file.path}}/{{each_config_file.filename}}"
    diff: yes
    with_items: "{{ conf_files }}"
    when: each_config_file.filename == "NFProfile.json"
    loop_control:
       loop_var: each_config_file
  notify:
      - stop {{deployment_type|lower}}
      - start {{deployment_type|lower}}

