- name: NSSF nsr templating
  template: src=nssf_nsr_mongo_json.j2 dest="{{item.nsr_name}}.json"
  diff: yes
  delegate_to: mongo

- name: Mongo import operation
  ansible.builtin.shell: mongoimport --mode upsert --db "{{db_name}}" --collection "{{nssf_nsr_profile_col_name}}" --file "{{item.nsr_name}}.json"
  delegate_to: mongo
