- name: copy dump files to container
  ansible.builtin.shell: docker cp  test_out/files/pcf_dump "{{mongo_container_name}}":/
  delegate_to: mongo

- name: Mongo restore operation "{{db_name}}"
  ansible.builtin.shell: docker exec -it "{{mongo_container_name}}" mongorestore --db {{db_name}} pcf_dump
  delegate_to: mongo

- name: AmfList templating
  template: src=pcf_profile_mongo_json.j2 dest="{{pcf_profile_col_name}}.json"
  diff: yes
  delegate_to: mongo

- name: copy templating file to container
  ansible.builtin.shell: docker cp  "{{pcf_profile_col_name}}.json" "{{mongo_container_name}}":/
  delegate_to: mongo

- name: Mongo import operation
  ansible.builtin.shell: docker exec -it "{{mongo_container_name}}" mongoimport --mode upsert --db "{{db_name}}" --collection "{{pcf_profile_col_name}}" --file "{{pcf_profile_col_name}}.json"
  delegate_to: mongo

